In [1]:
import pandas as pd
import numpy as np
import regex as re
import nltk   #natural language toolkit
nltk.download('stopwords')
from nltk.corpus import stopwords  #corpus means collection
stop=stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df=pd.read_csv('Tweets.csv')

In [3]:
df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,5.703060e+17,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,24/02/2015 11:35,NaN,Eastern Time (US & Canada)
1,5.703010e+17,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,24/02/2015 11:15,NaN,Pacific Time (US & Canada)
2,5.703010e+17,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,24/02/2015 11:15,Lets Play,Central Time (US & Canada)
3,5.703010e+17,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,24/02/2015 11:15,NaN,Pacific Time (US & Canada)
4,5.703010e+17,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,24/02/2015 11:14,NaN,Pacific Time (US & Canada)

In [4]:
df=df[['text','airline_sentiment']]

In [5]:
df.head()

                                                text airline_sentiment
0                @VirginAmerica What @dhepburn said.           neutral
1  @VirginAmerica plus you've added commercials t...          positive
2  @VirginAmerica I didn't today... Must mean I n...           neutral
3  @VirginAmerica it's really aggressive to blast...          negative
4  @VirginAmerica and it's a really big bad thing...          negative

## Data Cleaning

In [6]:
def clean_data(text):
    sentence=text.lower()   # converts the entire text into lower case
    sentence=re.sub('[^a-z]',' ',sentence)   # substitues all non alphabets symbol like @ with space
    words=sentence.split()  # splits the unique words in a sentence and stores in a list
    imp_words=[w for w in words if w not in stop]  #this filters out all the words which are not stop words
    return ' '.join(imp_words)    #join all words with space to form a sentence

In [7]:
df['cleaned_text']=df['text'].apply(lambda x: clean_data(x))  #we apply lambda so that this applies on each row

In [8]:
df.head()

,text,airline_sentiment,cleaned_text
0,@VirginAmerica What @dhepburn said.,neutral,virginamerica dhepburn said
1,@VirginAmerica plus you've added commercials t...,positive,virginamerica plus added commercials experienc...
2,@VirginAmerica I didn't today... Must mean I n...,neutral,virginamerica today must mean need take anothe...
3,@VirginAmerica it's really aggressive to blast...,negative,virginamerica really aggressive blast obnoxiou...
4,@VirginAmerica and it's a really big bad thing...,negative,virginamerica really big bad thing

In [10]:
df=df[['cleaned_text','airline_sentiment']]

In [12]:
df.to_csv('Cleaned_TweetsData.csv')